version: '2'
services:

  its-web-2020-app1:
    container_name: its-web-2020-app1
    hostname: its-web-2020-app1
    build:
      dockerfile: docker/app1/Dockerfile
      context: .
    ports:
    - "9000:9000"
    #environment:
    # environment variables can be set herein
    networks:
    - default

  its-web-2020-proxy:
    container_name: its-web-2020-proxy
    hostname: its-web-2020-proxy
    #    dockerfile: docker/nginx/Dockerfile
    #    context: .
    image: nginx
    ports:
      - 8000:8000
    depends_on:
      - its-web-2020-app1
    volumes:
      - ./docker/nginx/files/etc/nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
  default:
    driver: bridge
