---

- name: Installing base system utilities
  hosts: 127.0.0.1
  connection: local
  become: true
  tasks:

    - name: Installing aptitude
      apt: name="aptitude" state="present" update_cache="yes" force_apt_get="yes"
      register: task_result
      until: task_result is success
      retries: 1
      delay: 10

    - name: add universe repository for bionic
      apt_repository: 
        repo: deb http://archive.ubuntu.com/ubuntu bionic universe
        state: present

    - name: Add key for Postgres repo
      apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
      sudo: yes

    - name: Add Postgres repo to sources list
      apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt bionic-pgdg main' state=present
      sudo: yes

    - name: Base system update and upgrade
      become: true
      apt:
        upgrade: "yes"
        update_cache: "yes"
        cache_valid_time: 6000
        
    - name: Installing base system tools
      apt: name="nano,net-tools,nmap,ntpdate,git,python-apt,software-properties-common,apt-transport-https,ca-certificates,curl,gnupg-agent,python3-pip" state="present" update_cache="yes" force_apt_get="yes"
      register: task_result
      until: task_result is success
      retries: 1
      delay: 5

    - name: Base system update and upgrade
      become: true
      apt:
        upgrade: "yes"
        update_cache: "yes"
        cache_valid_time: 6000

    - name: Installing Postgres & Docker
      apt: name="postgresql-12,docker.io" state="present" update_cache="yes" force_apt_get="yes"
      register: task_result
      until: task_result is success
      retries: 1
      delay: 5

    - name: Enabling remote connections for postgresql
      lineinfile:
        dest: "/etc/postgresql/12/main/postgresql.conf"
        regexp: "listen_addresses"
        line: "listen_addresses = '*'"

    - name: Enabling loose access controls for postgresql
      copy:
        src: files/etc/postgresql
        dest: /etc/postgresql
        owner: postgres
        group: postgres
        mode: '0640'

- name: PHP7.4
  hosts: 127.0.0.1
  connection: local
  
  tasks:
    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

    #Apache Installation
    - name: Install Apache + PHP
      apt: name={{ item }} update_cache=yes
      loop: [ 'apache2=2.4*' ]

    - name: Set up Apache configuration
      copy:
        src: "files/etc/apache2/"
        dest: "/etc/apache2/"
        owner: root
        group: root
        mode: '0755'
    
    - name: Enable rewrite module for apache
      apache2_module:
        name: rewrite
        state: present

    - name: Copies Default Document Root Content
      copy:
        src: files/var/www/html/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Enable websites
      shell: find . -type f -and -not -name "*default*" -exec a2ensite {} \;
      args:
        chdir: /etc/apache2/sites-available
      register: websiteenable

    - name: Display enabled websites
      debug: msg="{{ websiteenable.stdout }}"

    #Apache + PHP Configuration
    - name: Install PHP + Deps
      apt: name={{ item }} update_cache=yes
      loop: [ "php7.2", "libapache2-mod-php7.2", "php7.2-common", "php7.2-cli", "php7.2-curl", "php7.2-gd", "php7.2-json", "php7.2-intl", "php7.2-mysql", "php7.2-pgsql", "php7.2-imap", "php7.2-bz2", "php7.2-bcmath", "php7.2-mbstring","php7.2-zip","php-redis", "npm"]

    # Conf PHP
    - name: Copies Apache PHP Configuration
      copy:
        src: files/etc/php/7.2/apache2/php.ini
        dest: /etc/php/7.2/apache2/php.ini
        owner: root
        group: root
        mode: '0611'

    - name: Copies PHP CLI Configuration
      copy:
        src: files/etc/php/7.2/cli/php.ini
        dest: /etc/php/7.2/cli/php.ini
        owner: root
        group: root
        mode: '0611'

    - name: copy session test
      copy:
        src: files/var/www/html/system-test.php
        dest: /var/www/html/system-test.php
        owner: www-data
        group: www-data
        mode: '0655'

    # UFW Configuration
    - name: "UFW - Allow HTTP on port 8080"
      ufw:
        rule: allow
        port: '8080'
        proto: tcp

    - name: Restart Apache
      service:
        name: apache2
        state: restarted

- name: phpPgAdmin 
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: install
    unarchive:
        src: https://github.com/phppgadmin/phppgadmin/archive/REL_5-6-0.tar.gz
        dest: /opt
        remote_src: yes
  # sudo: yes

  - name: Create symbolic link
    file:
      src: "/opt/phppgadmin-REL_5-6-0"
      dest: "/opt/pgad"
      state: link

  - name: copy configuration file
    copy:
      src: files/opt/pgad/conf/config.inc.php
      dest: /opt/pgad/conf/
      owner: www-data
      group: www-data
      mode: '0655'


- name: Nginx
  hosts: 127.0.0.1
  connection: local
  tasks:
  
    - name: install nginx and ensure it is at the latest version
      apt: name=nginx state=latest force_apt_get=yes
  
    - name: start nginx
      service:
          name: nginx
          state: started

    - name: Creates default document root
      file:
        path: "/var/www/html"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Creates default index page
      copy:
        src: files/var/www/html/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copies Default Document Root Content
      copy:
        src: files/var/www/html/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Set up Nginx configuration
      copy:
        src: "files/etc/nginx/"
        dest: "/etc/nginx/"
        owner: root
        group: root
        mode: '0755'

    - name: Enable proxies
      shell: find . -type f -exec ln -s /etc/nginx/sites-available/{} /etc/nginx/sites-enabled/{} \;
      args:
        chdir: /etc/nginx/sites-available
      register: websiteenable

    - name: Display enabled websites
      debug: msg="{{ websiteenable.stdout }}"

    #- name: Remove default configuration file (prevents nginx from starting)
    #  file:
    #    path: /etc/nginx/sites-enabled/default
    #    state: absent

    - name: Restart nginx
      service: name=nginx state=restarted

    # UFW Configuration
    - name: "UFW - Allow HTTP on port 80"
      ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: "UFW - Allow HTTP on port 443"
      ufw:
        rule: allow
        port: '443'
        proto: tcp

    - name: Execute the command in remote shell; stdout goes to the specified file on the remote
      shell: "curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -"

    #- name: Execute the command in remote shell; stdout goes to the specified file on the remote
    #  command: sudo apt-get install -y nodejs
    - name: Base system update and upgrade
      become: true
      apt:
        upgrade: "yes"
        update_cache: "yes"
        cache_valid_time: 6000
      
    - name: Installing NodeJS
      apt: name="nodejs" state="latest" update_cache="yes" force_apt_get="yes"
      register: task_result
      until: task_result is success
      retries: 2
      delay: 5